# fly.toml app configuration file generated for metrics-ui on 2025-10-10T11:00:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'metrics-ui'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
