# fly.toml app configuration file generated for carrier-loads on 2025-09-26T19:56:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'carrier-loads'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
