# fly.toml app configuration file generated for fmcsa-fake on 2025-09-26T20:03:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fmcsa-fake'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
